### ISSUE TITLE
IE performance

### ISSUE THREAD

**Issue by shiraaa** [mbebenita/Broadway#101]
Hi guys,
Thank you very much for this cool project.
I'm using this project in order to compress jpegs to mp4  for storage and decode back to jpegs when it needed. Because of that, decoding performance is very important for me.
I noticed that IE(v 11) performance are extremely slow(20-30 fps) in compare to Firefox and Chrome(150-190 fps). I also noticed that when I running my project(slightly different from Player code). The performance of IE is even worse (3-6 fps, Chrome and firefox stay the same) .
I really would like to insert the code to production, Do you know what may cause IE is to be so slow ? is it possible to improve it?
P.S, I read about the memory usage issue on MP4.js. I didn't fix it yet, do you think it's affect performance?
Thanks in advance.
Shira.

**Comment by soliton4** [comment]
hi @shiraaa 

the way i see it you have two options.
1. convince microsoft to support asm.js
2. convince your customers to not use microsoft browsers

microsoft browsers are to slow for broadway because as far as i know they dont support asm.js
i dont know if that changed with their newest product thou.

**Comment by shiraaa** [comment]
Thank you!
