### ISSUE TITLE
Kindly ask to be one of the contributors

### ISSUE THREAD

**Issue by ChihMin** [mbebenita/Broadway#133]
Hi, currently I have some performance tuning job for this project based on LLVM optimizer.

Now, I find some good "optimization flag combinations" that it can improve iframe decoding time about 30% ~ 60%.

I would like to contribute back to this project by modifying building script(make.py), what should I need to attach, for instance,  performance report, benchmark, performance tuning execution flow, experiment methods?

**Comment by soliton4** [comment]
Hi @ChihMin
are you familiar with pull requests?
i have a sophisticated testing environment. if your modifications will result in any significant performance changes i will see it.
i kindly ask you to create a pr.
everyone is welcome to contribute

**Comment by ChihMin** [comment]
Okay, I will issue a pull request after refactoring the code, thanks :D

**Comment by soliton4** [comment]
@ChihMin i gave your modifications a quick spin with the test pages included in this project.
so far i could not see a significant increase in fps which would suggest an increase in performance.
updating to the latest emscripten compiler resulted in about 3% better performace for both the latest master version and your changes.

maybe it would be a good idea to get some insights in your testing environment.
is there any chance i could contact you or have a video chat with you?
feel free to email me.
matthias.behrens@gmail.com

i will continue to evaluate your changes in a more detailed testing environment.

i have no problem pulling your changes but it would be helpful to actually know what you are doing since i cant make sense of most of the new parameters you are using.

maybe we could talk about that
