### ISSUE TITLE
work only Baseline ?

### ISSUE THREAD

**Issue by deepch** [mbebenita/Broadway#145]
i send decode 
Baseline - work nice
Stream #0:0: Video: h264 (Baseline), yuvj420p(pc, progressive), 640x480, 15 fps, 30 tbr, 90k tbn, 30 tbc

i send decode 

Main - not work 
Stream #0:0: Video: h264 (Main), yuv420p(progressive), 1280x720, 20 fps, 20 tbr, 90k tbn, 40 tbc

only supported Baseline ?

**Comment by soliton4** [comment]
i'm afraid so.
broadway supports only baseline profile right now.
if performance is less critical for you there is a way to compile openh264 to javascript.
but it is measurable slower than broadway at this point.
if you feel up to it you can try optimize it and let me know, i'll help integrate it into broadway

**Comment by deepch** [comment]
thanks for the answer.

It's a pity the idea is good that would show the rtsp -> web in this way but it's unfortunate that most of the cameras use main 

Maybe you plan add main profile later?

**Comment by soliton4** [comment]
broadway is compiled from the android h264 decoder sources.
it is highly optimized using the emscripten compile optimization parameters.
adding main or extended profile support to those sources is not an option for me.
there is however another open source h264 decoder called openh264
its easy to compile to emscripten and it would work in a similar way.
you can use the broadway canvas object to display the decoded result.
the trick is to optimize that compile process as good as broadway.
otherwise its noticably slower.

these links should help you get going
https://github.com/cisco/openh264
https://github.com/kazuki/video-codec.js
https://github.com/kripken/emscripten/blob/master/src/settings.js
https://github.com/mbebenita/Broadway/blob/master/Decoder/make.py

i am totally willing to assist you
