### ISSUE TITLE
Problem in AVC files from make.py 

### ISSUE THREAD

**Issue by saimamahmood** [mbebenita/Broadway#52]
Hi, 

I am trying to get the Broadway demo to work on my computer and I seem to have run into some problems. Apparently the avc.js and avs-codec.js files have not been properly handled when I run the make.py script. I was unable to run the demo, so I copied the source files from the demo's browser provided here, to pin point where the issue came from, being the 2 avc files. 

I simply ran the make.py script after downloading and configuring Emscripten. Is there anything that im missing at this step that I should take note of? Also the make.py script does not seem to create the Broadway.js and Decoder.js files. I compiled the corresponding C files manually to get the javascript. Is this right?

Thanks!
Saima

**Comment by soliton4** [comment]
@saimamahmood @mbebenita  i think i just fixed it


the newest version of emscripten makes a mem init file per default. while this may have some perfomance impact that i was not able to measure, it caused some serious problems

1. the .mem file was missing in the repos - could be easily fixed but:  
2. the usage of a memory initializing file makes it neccessary to use a callback function to start the asm.js code. the demo however doesnt do that properly. 

i had the effect that it loaded sometimes but sometimes not. on my laptop it worked in ff but not in chrome
on my desktop it worked in chrome but not in ff. also not in chrome private browsing mode.
turns out some cache mess causes the code to be sync sometimes and async another time.
i didnt want to go that deep into the matter so i changed it back to not use the mem file

refer to this if you want details:

http://kripken.github.io/emscripten-site/docs/optimizing/Optimizing-Code.html

the commit that fixes it is this:

https://github.com/mbebenita/Broadway/commit/736e9230f86baae6bdcd98c286aad9cf78e9965b


you can look forward to a integration of the fast worker, the asm.js code and i also plan to create a universal module loading header

best wishes

ps: pls close when satisfied

**Comment by saimamahmood** [comment]
Hi thanks for the reply, It works perfect now.
