### ISSUE TITLE
Is it possible to use Broadway to enable autoplay on mobile?

### ISSUE THREAD

**Issue by mcranston18** [mbebenita/Broadway#65]
Mobile browsers do not support the `autoplay` feature of HTML5 video.

```
<video src="myVideo.mp4" autoplay>
```

This will autoplay using non-mobile browsers but not on mobile browsers.

Is it possible to decode the MP4 and then autoplay it using Broadway?

**Comment by soliton4** [comment]
you will have to program the auto play logic yourself
broadway.js is only a decoder that gives you the video frame by frame

**Comment by alastaircoote** [comment]
It is entirely possible, but in my initial tests it doesn't achieve the FPS necessary (on an iPod Touch) to play a video. You'd also need to handle audio separately.

**Comment by mcranston18** [comment]
@alastaircoote would you be willing to post any code you've tried in experimenting with this?

**Comment by alastaircoote** [comment]
@mcranston18 I'm afraid I haven't experimented much beyond using the demo page in this repo. I've played around a little more with [JSMPEG](https://github.com/phoboslab/jsmpeg) - an MPEG1 decoder. File sizes are far larger, but it performs much better on mobile devices (presumably because the compression is less complex).

**Comment by mcranston18** [comment]
@alastaircoote thanks for the link! I appreciate the feedback.
